export default [
    "The Funnies",
    "Reticulating splines...",
    "Generating witty dialog...",
    "Swapping time and space...",
    "Spinning violently around the y-axis...",
    "Tokenizing real life...",
    "We need a new fuse...",
    "Have a good day.",
    "Upgrading Windows, your PC will restart several times. Sit back and relax.",
    "640K ought to be enough for anybody",
    "The architects are still drafting",
    "We're building the buildings as fast as we can",
    "Would you prefer chicken, steak, or tofu?",
    "(Pay no attention to the man behind the curtain)",
    "...and enjoy the elevator music...",
    "Please wait while the little elves draw your map",
    "Don't worry - a few bits tried to escape, but we caught them",
    "Would you like fries with that?",
    "Checking the gravitational constant in your locale...",
    "Go ahead -- hold your breath!",
    "...at least you're not on hold...",
    "Hum something loud while others stare",
    "The server is powered by a lemon and two electrodes.",
    "We're testing your patience",
    "As if you had any other choice",
    "Why don't you order a sandwich?",
    "While the satellite moves into position",
    "The bits are flowing slowly today",
    "It's still faster than you could draw it",
    "The last time I tried this the monkey didn't survive. Let's hope it works better this time.",
    "I should have had a V8 this morning.",
    "My other loading screen is much faster.",
    "Testing on Timmy... We're going to need another Timmy.",
    "(Insert quarter)",
    "Are we there yet?",
    "Have you lost weight?",
    "Just count to 10",
    "Why so serious?",
    "It's not you. It's me.",
    "Counting backwards from Infinity",
    "Don't panic...",
    "Do not run! We are your friends!",
    "Do you come here often?",
    "Warning: Don't set yourself on fire.",
    "We're making you a cookie.",
    "Creating time-loop inversion field",
    "Spinning the wheel of fortune...",
    "Computing chance of success",
    "Looking for exact change",
    "I feel like im supposed to be loading something. . .",
    "Is this Windows?",
    "Adjusting flux capacitor...",
    "Don't break your screen yet!",
    "I swear it's almost done.",
    "Almost there...",
    "Let's take a mindfulness minute...",
    "Listening for the sound of one hand clapping...",
    "Keeping all the 1's and removing all the 0's...",
    "Putting the icing on the cake. ",
    "Cleaning off the cobwebs...",
    "Making sure all the i's have dots...",
    "We are not liable for any broken screens as a result of waiting.",
    "Granting wishes...",
    "Time flies when you’re having fun.",
    "Get some coffee and come back in ten minutes..",
    "Spinning the hamster…",
    "Stay awhile and listen..",
    "You shall not pass! yet..",
    "Load it and they will come",
    "Convincing AI not to turn evil..",
    "Your left thumb points to the right and your right thumb points to the left.",
    "How did you get here?",
    "Wait, do you smell something burning?",
    "Computing the secret to life, the universe, and everything.",
    "When nothing is going right, go left!!...",
    "I love my job only when I'm on vacation...",
    "i'm not lazy, I'm just relaxed!!",
    "Never steal. The government hates competition....",
    "Why are they called apartments if they are all stuck together?",
    "Life is Short – Talk Fast!!!!",
    "Optimism – is a lack of information.....",
    "Save water and shower together",
    "Whenever I find the key to success, someone changes the lock.",
    "Adults are just kids with money.",
    "I think I am, therefore, I am. I think.",
    "A kiss is like a fight, with mouths.",
    "You don’t pay taxes—they take taxes.",
    "A commit a day keeps the mobs away",
    "Anyone else stan Bad Bunny?",
    "Constructing additional pylons...",
    "We are not liable for any broken screens as a result of waiting.",
    "Hello IT, have you tried turning it off and on again?",
    "If you type Google into Google you can break the internet",
    "Well, this is embarrassing.",
    "Hello, IT... Have you tried forcing an unexpected reboot?",
    "Didn't know paint dried so quickly.",
    "Everything sounds the same",
    "I'm going to walk the dog",
    "I didn't choose the engineering life. The engineering life chose me.",
    "Dividing by zero...",
    "Spawn more Overlord!",
    "If I’m not back in five minutes, just wait longer.",
    "Some days, you just can’t get rid of a bug!",
    "We’re going to need a bigger boat.",
    "Web developers do it with <style>",
    "Java developers never RIP. They just get Garbage Collected.",
    "Cracking military-grade encryption...",
    "Simulating traveling salesman...",
    "Proving P=NP...",
    "Entangling superstrings...",
    "Twiddling thumbs...",
    "Searching for plot device...",
    "Trying to sort in O(n)...",
    "Laughing at your pictures-i mean, loading...",
    "Sending data to NS-i mean, our servers.",
    "Looking for sense of humour, please hold on.",
    "Please wait while the intern refills his coffee.",
    "A different error message? Finally, some progress!",
    "Hold on while we wrap up our git together...sorry",
    "Please hold on as we reheat our coffee",
    "We will return from our lunch break in 30 mins",
    "Kindly hold on as we convert this bug to a feature...",
    "Kindly hold on as our intern quits vim...",
    "Winter is coming...",
    "Installing dependencies",
    "Switching to the latest JS framework...",
    "Distracted by cat vids",
    "Finding someone to hold my beer",
    "BRB, working on my side project",
    "@todo Insert witty loading message",
    "Let's hope it's worth the wait",
    "Aw, snap! Not..",
    "Ordering 1s and 0s...",
    "Updating dependencies...",
    "Whatever you do, don't look behind you...",
    "Please wait... Consulting the manual...",
    "Loading funny message...",
    "Waiting Daenerys say all her titles...",
    "Feel free to spin in your chair",
    "What the what?",
    "formatting ...",
    "Shoot your shot and slide into the DM's",
    "What's under there?",
    "Your computer has a virus, its name is Windows!",
    "Don't hold your breath...",
    "Bored of slow loading spinner, buy more RAM!",
    "Help, I'm trapped in a loader!",
    "Mining some bitcoins...",
    "Downloading more RAM..",
    "Updating to Windows Vista...",
    "Deleting System32 folder",
    "Hiding all ;'s in your code",
    "Alt-F4 speeds things up.",
    "Initializing the initializer...",
    "When was the last time you dusted around here?",
    "Optimizing the optimizer...",
    "Last call for the data bus! All aboard!",
    "Running swag sticker detection...",
    "When nothing is going right, go left!",
    "Never let a computer know you're in a hurry.",
    "Some things man was never meant to know. For everything else, there's Google.",
    "Shovelling coal into the server",
    "Pushing pixels...",
    "How about this weather, eh?",
    "The severity of your issue is always lower than you expected.",
    "Updating Updater...",
    "Downloading Downloader...",
    "Debugging Debugger...",
    "Reading Terms and Conditions for you.",
    "Digested cookies being baked again.",
    "Live long and prosper.",
    "Running with scissors...",
    "Definitely not a virus...",
    "All you had to do is to commit the damn funnies, CJ!",
    "Throw some cash into the night sky, call it Starbucks",
    "You seem like a nice person...",
    "Coffee at my place, tommorow at 10A.M. - don't be late!",
    "Work, work...",
    "Patience! This is difficult, you know...",
    "Discovering new ways of making you wait...",
    "Your time is very important to us. Please wait while we ignore you...",
    "Time flies like an arrow; fruit flies like a banana",
    "Two men walked into a bar; the third ducked...",
    "TODO: Insert elevator music",
    "Still faster than Windows update",
    "Obfuscating quantum entaglement",
    "Go to class!",
    "UC or CSU...?",
    "If at first you don't succeed, call it version 1.0.",
    "Preventing robot uprising ...",
    "Hacking into the Main Frame...",
    "Installing virus...",
    "Loading Error...",
    "PC LOAD LETTER...",
    "Waiting for something to load sucks...",
    "Deleting system32...",
    "CTRL + C, CTRL + V",
    "Remember when Squidward hit the whoa?",
    "Remember vine?",
    "Make me TikTok famous",
    "Oh, are you waiting for me?",
    "Do you smell carrots? -a snowman",
    "That job was a piece of cake",
    "Hint - You can swipe down from the top to reload the page",
    "Do you have 5G?",
    "Oh you are an eager beaver",
    "Wildfire called they want their app back",
    "Going to buy milk brb",
    "He makes a monkey business", 
    "The Game - you just lost it.",
    "Maybe it's time to upgrade your internet...",
    "Android or IOS?",
  ];